FROM node:16-slim as builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npx nx build codeheroes-api --configuration=production


FROM node:16-slim
ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}
WORKDIR /app
COPY package.json ./
RUN npm install -only=production
COPY --from=builder /app/dist/apps/codeheroes-api ./
CMD node ./main.js
